CREATE TABLE "PERSON" (
	"ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"FIRSTNAME" CHAR(250) NOT NULL,
	"LASTNAME" CHAR(250) NOT NULL,
	"NO_ACCOUNTSYSTEM" CHAR(250) NOT NULL,
	CONSTRAINT UNIQUE_PERSON_NO_ACCOUNTSYSTEM UNIQUE ("NO_ACCOUNTSYSTEM")
);

CREATE TABLE "EXPENSES" (
	"ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"NO_ACCOUNTSYSTEM" CHAR(250) NOT NULL,
	"EXPENSE" NUMERIC NOT NULL,
	CONSTRAINT primary_key PRIMARY KEY (id),
	CONSTRAINT FK_PERSON foreign key(NO_ACCOUNTSYSTEM) references PERSON(NO_ACCOUNTSYSTEM)
);

insert into PERSON(FIRSTNAME , LASTNAME, NO_ACCOUNTSYSTEM) values('Ivan' , 'Ivanoc', 'i01');
insert into PERSON(FIRSTNAME , LASTNAME, NO_ACCOUNTSYSTEM) values('Pert' , 'Petrov', 'p02');
insert into EXPENSES(NO_ACCOUNTSYSTEM , EXPENSE) values('i01' , 100);
insert into EXPENSES(NO_ACCOUNTSYSTEM , EXPENSE) values('i01' , 100);
insert into EXPENSES(NO_ACCOUNTSYSTEM , EXPENSE) values('i01' , 100);
insert into EXPENSES(NO_ACCOUNTSYSTEM , EXPENSE) values('p02' , 100);
insert into EXPENSES(NO_ACCOUNTSYSTEM , EXPENSE) values('p02' , 100);