
package com.epam.training.module15.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChampionshipServiceService", targetNamespace = "http://service.module15.training.epam.com/", wsdlLocation = "http://localhost:9876/ws/ChampionshipService?wsdl")
public class ChampionshipServiceService
    extends Service
{

    private final static URL CHAMPIONSHIPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CHAMPIONSHIPSERVICESERVICE_EXCEPTION;
    private final static QName CHAMPIONSHIPSERVICESERVICE_QNAME = new QName("http://service.module15.training.epam.com/", "ChampionshipServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9876/ws/ChampionshipService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHAMPIONSHIPSERVICESERVICE_WSDL_LOCATION = url;
        CHAMPIONSHIPSERVICESERVICE_EXCEPTION = e;
    }

    public ChampionshipServiceService() {
        super(__getWsdlLocation(), CHAMPIONSHIPSERVICESERVICE_QNAME);
    }

    public ChampionshipServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHAMPIONSHIPSERVICESERVICE_QNAME, features);
    }

    public ChampionshipServiceService(URL wsdlLocation) {
        super(wsdlLocation, CHAMPIONSHIPSERVICESERVICE_QNAME);
    }

    public ChampionshipServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHAMPIONSHIPSERVICESERVICE_QNAME, features);
    }

    public ChampionshipServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChampionshipServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChampionshipService
     */
    @WebEndpoint(name = "ChampionshipServicePort")
    public ChampionshipService getChampionshipServicePort() {
        return super.getPort(new QName("http://service.module15.training.epam.com/", "ChampionshipServicePort"), ChampionshipService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChampionshipService
     */
    @WebEndpoint(name = "ChampionshipServicePort")
    public ChampionshipService getChampionshipServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.module15.training.epam.com/", "ChampionshipServicePort"), ChampionshipService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHAMPIONSHIPSERVICESERVICE_EXCEPTION!= null) {
            throw CHAMPIONSHIPSERVICESERVICE_EXCEPTION;
        }
        return CHAMPIONSHIPSERVICESERVICE_WSDL_LOCATION;
    }

}
