
package com.epam.training.module15.model;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChampionshipService", targetNamespace = "http://service.module15.training.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChampionshipService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.epam.training.module15.model.WeatherInCity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWeatherInCity", targetNamespace = "http://service.module15.training.epam.com/", className = "com.epam.training.module15.model.GetWeatherInCity")
    @ResponseWrapper(localName = "getWeatherInCityResponse", targetNamespace = "http://service.module15.training.epam.com/", className = "com.epam.training.module15.model.GetWeatherInCityResponse")
    public List<WeatherInCity> getWeatherInCity(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.training.module15.model.TotalCard
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cardsPerTeam", targetNamespace = "http://service.module15.training.epam.com/", className = "com.epam.training.module15.model.CardsPerTeam")
    @ResponseWrapper(localName = "cardsPerTeamResponse", targetNamespace = "http://service.module15.training.epam.com/", className = "com.epam.training.module15.model.CardsPerTeamResponse")
    public TotalCard cardsPerTeam(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
